#!/usr/bin/env instantfpc
program Bootstrap;

{ Bootstrap LWPT for the first build of a fresh clone (or after
  `lwpt build --clean`). Produces build/lwpt, after which
  ./build/lwpt build is the canonical build entry point.

  Single responsibility: invoke fpc once to compile source/lwpt.pas
  -> build/lwpt, passing -Fu / -Fi for each workspace package's
  source dir so cold compilation succeeds without going through
  `lwpt install` first.

  earlier this script also regenerated source/LWPT.Embedded.TestingLibrary.inc
  from the canonical TestingPascalLibrary.pas + Shared.inc. ADR-0015
  graduated the testing framework to packages/testing/ as a workspace
  package, so the embed-blob plumbing is gone and bootstrap's only job
  is the single fpc invocation below.

  Compiler flags here MUST stay in sync with the dev-mode flags in
  AddBuildModeFlags inside source/LWPT.Command.Build.pas. The bootstrap only
  ever performs a dev build; release builds always go through
  ./build/lwpt build --mode release.

  Must be invoked with the repo root as the working directory.
  The shell wrappers bootstrap.sh / bootstrap.bat take care of that. }

{$mode objfpc}{$H+}

uses
  Classes, SysUtils, Process;

const
  BUILD_DIR      = 'build';
  OUTPUT_BINARY  = 'build/lwpt';
  SOURCE_DIR     = 'source';
  PROGRAM_SOURCE = 'source/lwpt.pas';
  MANIFEST_PATH  = 'lwpt.toml';
  VERSION_INC    = 'source/Version.inc';

{ Inline copy of scripts/stamp-version.pas's logic. The cold bootstrap
  cannot shell out to InstantFPC for the generator (instantfpc might not
  be on PATH yet on the very first build), so we inline the manifest
  parse + Version.inc write. The standalone scripts/stamp-version.pas
  exists for the [prebuild] hook used by steady-state `lwpt build`. }
function ExtractVersion(const ALines: TStringList): string;
var
  i, EqPos : Integer;
  Trimmed, Value : string;
  InPackage : Boolean;
begin
  Result := '';
  InPackage := False;
  for i := 0 to ALines.Count - 1 do
  begin
    Trimmed := Trim(ALines[i]);
    if Trimmed = '' then Continue;
    if (Length(Trimmed) > 0) and (Trimmed[1] = '#') then Continue;
    if (Length(Trimmed) >= 2) and (Trimmed[1] = '[') then
    begin
      InPackage := SameText(Trimmed, '[package]');
      Continue;
    end;
    if not InPackage then Continue;
    if not SameText(Copy(Trimmed, 1, 7), 'version') then Continue;
    EqPos := Pos('=', Trimmed);
    if EqPos = 0 then Continue;
    Value := Trim(Copy(Trimmed, EqPos + 1, MaxInt));
    Value := StringReplace(Value, '"', '', [rfReplaceAll]);
    Value := StringReplace(Value, '''', '', [rfReplaceAll]);
    Result := Trim(Value);
    Exit;
  end;
end;

procedure StampVersion;
var
  Lines, Output: TStringList;
  Version: string;
begin
  Lines := TStringList.Create;
  try
    if not FileExists(MANIFEST_PATH) then
      raise Exception.CreateFmt('bootstrap: %s not found (run from repo root)',
        [MANIFEST_PATH]);
    Lines.LoadFromFile(MANIFEST_PATH);
    Version := ExtractVersion(Lines);
    if Version = '' then
      raise Exception.CreateFmt(
        'bootstrap: no `version` field in [package] of %s', [MANIFEST_PATH]);

    Output := TStringList.Create;
    try
      { Byte-identical to stamp-version.pas's manifest-case output, so a
        bootstrap after a stamped build leaves Version.inc unchanged. }
      Output.Add('{ Auto-generated by scripts/stamp-version.pas. Do not hand-edit. }');
      Output.Add('{ Source: [package].version in ' + MANIFEST_PATH + '. }');
      Output.Add('');
      Output.Add('  PROGRAM_VERSION = ' + QuotedStr(Version) + ';');
      Output.SaveToFile(VERSION_INC);
    finally
      Output.Free;
    end;
    WriteLn('bootstrap: stamped ', VERSION_INC, ' = ', Version);
  finally
    Lines.Free;
  end;
end;

function RunProcess(const Exe: string; const Args: array of string): Integer;
var
  P: TProcess;
  i: Integer;
begin
  P := TProcess.Create(nil);
  try
    P.Executable := Exe;
    for i := 0 to High(Args) do P.Parameters.Add(Args[i]);
    P.Options := [poWaitOnExit];
    P.Execute;
    Result := P.ExitStatus;
  finally
    P.Free;
  end;
end;

procedure CompileLwpt;
var
  Code: Integer;
begin
  ForceDirectories(BUILD_DIR);
  WriteLn('bootstrap: compiling ', PROGRAM_SOURCE, ' -> ', OUTPUT_BINARY);
  { Dev flags only. Mirrors AddBuildModeFlags' dev branch in LWPT.Command.Build;
    keep in sync until scripts/bootstrap-flags.inc is introduced. }
  Code := RunProcess('fpc',
    [ '-Mdelphi', '-Sh',
      '-O-',  '-gw', '-godwarfsets', '-gl',
      '-Ct',  '-Cr', '-Sa',
      '-FE' + BUILD_DIR,
      '-Fu' + SOURCE_DIR,
      '-Fi' + SOURCE_DIR,
      { Workspace packages live under packages/<name>/source/ per
        ADR-0014 (and ADR-0015 for `testing`). Bootstrap compiles
        against them directly; steady-state `lwpt build` reads them
        from .lwpt/modules/<name>/source/ via the symlinks the
        workspace install creates. }
      '-Fupackages/httpclient/source', '-Fipackages/httpclient/source',
      '-Fupackages/cli/source',        '-Fipackages/cli/source',
      '-Fupackages/semver/source',     '-Fipackages/semver/source',
      '-Fupackages/toml/source',       '-Fipackages/toml/source',
      '-Fupackages/testing/source',    '-Fipackages/testing/source',
      '-o' + OUTPUT_BINARY,
      PROGRAM_SOURCE ]);
  if Code <> 0 then
    raise Exception.CreateFmt(
      'bootstrap: fpc compile failed (exit %d)', [Code]);
end;

begin
  try
    StampVersion;
    CompileLwpt;
    WriteLn('bootstrap complete: ', OUTPUT_BINARY);
  except
    on E: Exception do
    begin
      WriteLn(ErrOutput, E.Message);
      ExitCode := 1;
    end;
  end;
end.
