#!/usr/bin/env instantfpc
program StampVersion;

{ Read [package].version from lwpt.toml and write source/Version.inc with
  a Pascal `PROGRAM_VERSION = '<value>';` constant. LWPT.Core.pas {$I}'s
  the result; lwpt --version reports the value.

  Single source of truth for the binary's version: the manifest field.
  This script is wired into lwpt.toml's [prebuild] hook (staleness-gated
  by ADR-0011 — re-runs only when lwpt.toml is newer than Version.inc)
  and into scripts/bootstrap.pas's cold build (always re-runs, so a
  fresh-clone build sees the current manifest value).

  Deliberately self-contained — does not depend on packages/toml so the
  bootstrap chicken-and-egg (lwpt cannot resolve its own deps before the
  binary exists) is preserved. The parser is a naive line scan for the
  first `version = "..."` line inside the [package] section; anything
  fancier (multi-section TOML state machine) would pull in packages/toml. }

{$mode delphi}{$H+}

uses
  Classes, SysUtils;

const
  MANIFEST_PATH = 'lwpt.toml';
  OUTPUT_PATH   = 'source/Version.inc';

function ExtractVersion(const ALines: TStringList): string;
var
  i, EqPos : Integer;
  Line, Trimmed, Value : string;
  InPackage : Boolean;
begin
  Result := '';
  InPackage := False;
  for i := 0 to ALines.Count - 1 do
  begin
    Trimmed := Trim(ALines[i]);
    if Trimmed = '' then Continue;
    if (Length(Trimmed) > 0) and (Trimmed[1] = '#') then Continue;

    if (Length(Trimmed) >= 2) and (Trimmed[1] = '[') then
    begin
      InPackage := SameText(Trimmed, '[package]');
      Continue;
    end;

    if not InPackage then Continue;

    Line := Trimmed;
    if not SameText(Copy(Line, 1, 7), 'version') then Continue;

    EqPos := Pos('=', Line);
    if EqPos = 0 then Continue;

    Value := Trim(Copy(Line, EqPos + 1, MaxInt));
    Value := StringReplace(Value, '"', '', [rfReplaceAll]);
    Value := StringReplace(Value, '''', '', [rfReplaceAll]);
    Result := Trim(Value);
    Exit;
  end;
end;

var
  Lines  : TStringList;
  Version: string;
  Out    : TStringList;
begin
  try
    if not FileExists(MANIFEST_PATH) then
    begin
      WriteLn(ErrOutput, 'stamp-version: ', MANIFEST_PATH,
        ' not found (run from repo root)');
      Halt(1);
    end;

    Lines := TStringList.Create;
    try
      Lines.LoadFromFile(MANIFEST_PATH);
      Version := ExtractVersion(Lines);
    finally
      Lines.Free;
    end;

    if Version = '' then
    begin
      WriteLn(ErrOutput, 'stamp-version: no `version` field in [package] of ',
        MANIFEST_PATH);
      Halt(1);
    end;

    Out := TStringList.Create;
    try
      Out.Add('{ Auto-generated by scripts/stamp-version.pas. Do not hand-edit. }');
      Out.Add('{ Sourced from [package].version in ' + MANIFEST_PATH + '. }');
      Out.Add('');
      Out.Add('  PROGRAM_VERSION = ' + QuotedStr(Version) + ';');
      Out.SaveToFile(OUTPUT_PATH);
    finally
      Out.Free;
    end;

    WriteLn('stamp-version: wrote ', OUTPUT_PATH, ' = ', Version);
  except
    on E: Exception do
    begin
      WriteLn(ErrOutput, 'stamp-version: ', E.Message);
      Halt(1);
    end;
  end;
end.
