{ LWPT.Command.Init — init subcommand entrypoint. }
unit LWPT.Command.Init;

{$I Shared.inc}
{$J-}
{$modeswitch nestedcomments+}

interface

procedure CmdInit(AYes, AForce: Boolean);

implementation

uses
  Classes,
  SysUtils,

  CLI.Prompts,
  LWPT.Command.Build,
  LWPT.Command.Install,
  LWPT.Core;

{
  CmdInit (ADR-0010) — scaffold a new LWPT project. Interactive by
  default; --yes (-y) uses defaults derived from the CWD's basename
  (npm-init-y style). Refuses to overwrite an existing lwpt.toml
  unless --force is also passed.
  =========================================================================== }
procedure WriteScaffoldManifest(const APath, AName, AVersion,
  ASourceDir, ABuildDir, AEntryName: string);
var SL: TStringList;
begin
  SL := TStringList.Create;
  try
    SL.Add('# ' + PROGRAM_NAME + '.toml — generated by `' + PROGRAM_NAME
           + ' init`. Edit me.');
    SL.Add('');
    SL.Add('[package]');
    SL.Add('name = "' + AName + '"');
    SL.Add('version = "' + AVersion + '"');
    SL.Add('units = ["' + ASourceDir + '"]');
    SL.Add('');
    SL.Add('[build]');
    SL.Add(AEntryName + ' = { source = "' + ASourceDir + '/'
           + AEntryName + '.pas", output = "' + ABuildDir + '/'
           + AEntryName + '" }');
    SL.Add('');
    SL.Add('# [dependencies]');
    SL.Add('# horse = "HashLoad/horse@^4.0.0"               # GitHub by default');
    SL.Add('# ci-debug = "gitlab:gitlab-examples/ci-debug-trace@dd648b2e48ce6518303b0bb580b2ee32fadaf045"');
    SL.Add('# leaf = "../leaf"                               # local path');
    SL.Add('# See ADR-0009 for the full source-spec syntax.');
    SL.Add('');
    SL.Add('# [sources]   — custom git-host prefixes; see ADR-0009.');
    SL.Add('# gitea = { archive = "https://git.example.com/{user}/{repository}/archive/{ref}.tar.gz", git = "https://git.example.com/{user}/{repository}.git" }');
    SL.SaveToFile(APath);
  finally
    SL.Free;
  end;
end;

{ Package names + entry names follow LWPT's project-name grammar, while
  `program X;` must be a Pascal identifier. The filename + target name +
  greeting text keep the original spelling — FPC doesn't require the
  program name to match the filename, so this stays out of the user's way. }
function SanitisePascalIdent(const S: string): string;
var i: Integer;
begin
  Result := '';
  for i := 1 to Length(S) do
    if (S[i] in ['a'..'z']) or (S[i] in ['A'..'Z'])
       or (S[i] in ['0'..'9']) or (S[i] = '_') then
      Result := Result + S[i]
    else
      Result := Result + '_';
  if Result = '' then
    Result := '_';
  if Result[1] in ['0'..'9'] then
    Result := '_' + Result;
end;

procedure WriteHelloProgram(const APath, AEntryName: string);
var SL: TStringList;
begin
  ForceDirectories(ExtractFileDir(APath));
  SL := TStringList.Create;
  try
    SL.Add('program ' + SanitisePascalIdent(AEntryName) + ';');
    SL.Add('');
    SL.Add('{$mode delphi}{$H+}');
    SL.Add('');
    SL.Add('begin');
    SL.Add('  WriteLn(''hello from ' + AEntryName + ''');');
    SL.Add('end.');
    SL.SaveToFile(APath);
  finally
    SL.Free;
  end;
end;

procedure EnsureGitignoreEntries(const APath: string;
  const ABuildDir: string);
var
  Wanted: TStringArray;
  SL: TStringList;
  i, j: Integer;
  Existed, HasEntry: Boolean;
  Added: Integer;
begin
  SetLength(Wanted, 3);
  Wanted[0] := '.lwpt/tmp/';
  Wanted[1] := '.lwpt/install.lock';
  Wanted[2] := StringReplace(IncludeTrailingPathDelimiter(ABuildDir),
    DirectorySeparator, '/', [rfReplaceAll]);
  Existed := FileExists(APath);
  SL := TStringList.Create;
  try
    if Existed then SL.LoadFromFile(APath);
    Added := 0;
    for i := 0 to High(Wanted) do
    begin
      HasEntry := False;
      for j := 0 to SL.Count - 1 do
        if Trim(SL[j]) = Wanted[i] then begin HasEntry := True; Break; end;
      if not HasEntry then
      begin
        if (SL.Count > 0) and (Trim(SL[SL.Count - 1]) <> '') then
          SL.Add('');
        if not Existed and (Added = 0) then
          SL.Add('# generated by `' + PROGRAM_NAME + ' init`');
        SL.Add(Wanted[i]);
        Inc(Added);
      end;
    end;
    if Added > 0 then SL.SaveToFile(APath);
  finally
    SL.Free;
  end;
end;

function ValidPackageName(const S: string): Boolean;
var i: Integer;
begin
  Result := False;
  if S = '' then Exit;
  for i := 1 to Length(S) do
    if not ((S[i] in ['a'..'z']) or (S[i] in ['A'..'Z'])
            or (S[i] in ['0'..'9']) or (S[i] = '-') or (S[i] = '_')) then
      Exit;
  Result := True;
end;

procedure CmdInit(AYes, AForce: Boolean);
const
  DEFAULT_VERSION    = '0.1.0';
  DEFAULT_SOURCE_DIR = 'source';
  DEFAULT_BUILD_DIR  = 'build';
var
  Name, Version, SourceDir, BuildDir, EntryName, CWD, EntryPath: string;
begin
  CWD := GetCurrentDir;
  if FileExists(MANIFEST_FILE) and not AForce then
    raise EManifestError.CreateFmt(
      '%s already exists in %s. Pass --force to overwrite, or '
      + 'remove the file first if you really mean to re-init.',
      [MANIFEST_FILE, CWD]);

  { Defaults derived from the CWD basename. Stripping a trailing
    path delimiter handles "/Users/foo/myproj/" → "myproj". }
  Name := ExtractFileName(ExcludeTrailingPathDelimiter(CWD));
  if (Name = '') or not ValidPackageName(Name) then Name := 'lwpt-project';
  Version   := DEFAULT_VERSION;
  SourceDir := DEFAULT_SOURCE_DIR;
  BuildDir  := DEFAULT_BUILD_DIR;
  EntryName := Name;

  if not AYes then
  begin
    WriteLn('initialising new ', PROJECT_NAME, ' project in ', CWD);
    WriteLn('press <enter> to accept the default in parentheses.');
    WriteLn;
    Name      := ReadPromptLine('package name',        Name);
    if not ValidPackageName(Name) then
      raise EManifestError.CreateFmt(
        'package name "%s" is not a valid identifier (must be ASCII '
        + 'letters/digits/hyphen/underscore)', [Name]);
    Version   := ReadPromptLine('version',             Version);
    SourceDir := ReadPromptLine('source folder',       SourceDir);
    BuildDir  := ReadPromptLine('build folder',        BuildDir);
    { Entry name default tracks the (possibly edited) package name —
      if you typed a new name in the first prompt, the entry should
      follow unless explicitly overridden. }
    if EntryName <> Name then EntryName := Name;
    EntryName := ReadPromptLine('project entry name',  EntryName);
    if not ValidPackageName(EntryName) then
      raise EManifestError.CreateFmt(
        'entry name "%s" is not a valid identifier (must be ASCII '
        + 'letters/digits/hyphen/underscore)', [EntryName]);
  end;

  EntryPath := SourceDir + '/' + EntryName + '.pas';
  WriteScaffoldManifest(MANIFEST_FILE, Name, Version,
    SourceDir, BuildDir, EntryName);
  WriteHelloProgram(EntryPath, EntryName);
  EnsureGitignoreEntries('.gitignore', BuildDir);

  WriteLn;
  WriteLn('initialized ', Name, ' v', Version);
  WriteLn('  ', MANIFEST_FILE, '   (manifest)');
  WriteLn('  ', EntryPath,     '   (hello-world entry)');
  WriteLn('  .gitignore       (entries appended)');
  WriteLn;

  { Post-init install + build chain. Interactive mode prompts (Y
    default) before running them so the user can opt out; --yes
    SKIPS the prompt + skips the actions (just the scaffold, the
    user runs install/build themselves). The lockfile is created
    by `lwpt install`, not by init — no need for an empty stub. }
  if AYes then
  begin
    WriteLn('next: `', PROGRAM_NAME, ' install` then `',
            PROGRAM_NAME, ' build` to fetch deps + compile.');
    Exit;
  end;

  if PromptYesNo('run `' + PROGRAM_NAME + ' install` and `'
    + PROGRAM_NAME + ' build` now?', True) then
  begin
    WriteLn;
    WriteLn('--- ', PROGRAM_NAME, ' install ---');
    CmdInstall(MANIFEST_FILE, False);
    WriteLn;
    WriteLn('--- ', PROGRAM_NAME, ' build ---');
    CmdBuild(MANIFEST_FILE, '', False, False);
    WriteLn;
    WriteLn('Run ./', BuildDir, '/', EntryName, ' to try it.');
  end
  else
    WriteLn('skipped install + build. Run `', PROGRAM_NAME,
            ' install` then `', PROGRAM_NAME, ' build` when ready.');
end;

end.
